 //Example Penulisan List Product,               
                
                // id: 6,
                // title: "Wireless Charger 3-in-1",
                // originalPrice: 799900,
                // price: 499900,
                // description: "Deskripsi barang",
                // category: "Aksesoris",
                // image: "#",
                // rating: "★★★☆☆", 
                // badge: "Diskon",
                // stock: 12,
                // detailUrl: "#"

 //Example penulisan
            // {
            //     id: 1,
            //     title: "",
            //     originalPrice: 0,
            //     price: 0,
            //     description: "",
            //     image: "/assets/img/.png",
            //     stock: 20,
            // }

// Product data array
        const products = [
            {
                id: 1,
                title: "Boiler 20 Liter",
                originalPrice: 4900000,
                price: 4800000,
                description: "Tingkatkan efisiensi usaha laundry Anda dengan **Boiler Uap 20 Liter** yang dirancang khusus untuk menghasilkan uap panas secara stabil dan maksimal, ideal untuk menyetrika lebih cepat dan hasil lebih licin. Terbuat dari material tahan karat dan hemat gas, boiler ini cocok untuk operasional harian laundry skala kecil hingga menengah. Dengan kapasitas yang pas dan sistem pengaman otomatis, Anda bisa bekerja lebih aman, hemat, dan profesional. Pilihan tepat untuk Anda yang ingin usaha makin lancar dan pelanggan makin puas!",
                image: "/assets/img/Boiler20L.png",
                stock: 3
            },
            {
                id: 2,
                title: "Box Coin Kecil",
                originalPrice: 10000000,
                price: 8000000,
                description: "Box Coin Laundry adalah solusi cerdas untuk mengubah mesin cuci biasa menjadi sistem laundry self-service yang praktis dan menguntungkan! Dilengkapi dengan sistem koin atau token otomatis, box ini memudahkan pengelolaan pembayaran tanpa perlu penjaga. Terbuat dari material kuat dan anti-karat, cocok untuk pemakaian jangka panjang di area publik. Instalasi mudah, kompatibel dengan berbagai tipe mesin cuci, dan siap membantu Anda membuka usaha laundry koin dengan modal terjangkau tapi hasil maksimal!",
                image: "/assets/img/BoxCoin.png",
                stock: 5,
            },
            {
                id: 3,
                title: "Coin Changer",
                originalPrice: 59000000,
                price: 55000000,
                description: "Mesin ATM Coin Changer adalah perangkat pintar yang memudahkan pelanggan menukar uang kertas menjadi koin atau token secara otomatis, ideal untuk usaha laundry koin, tempat bermain, atau fasilitas self-service lainnya. Dengan sistem digital yang akurat dan responsif, mesin ini membantu operasional bisnis berjalan lancar tanpa perlu penjaga. Desain modern, mudah digunakan, serta dilengkapi fitur keamanan untuk melindungi transaksi. Cocok untuk meningkatkan profesionalisme layanan dan kenyamanan pelanggan Anda!",
                image: "/assets/img/CoinChanger.png",
                stock: 5,
            },
            {
                id: 4,
                title: "Detergent 5 Liter",
                originalPrice: 68000,
                price: 50000,
                description: "Detergent Cair 5 Liter ini diformulasikan khusus untuk membersihkan pakaian secara menyeluruh, mengangkat noda membandel tanpa merusak serat kain, serta memberikan aroma segar yang tahan lama. Cocok untuk kebutuhan laundry rumahan maupun usaha laundry profesional, deterjen ini menghasilkan busa melimpah, mudah dibilas, dan aman untuk semua jenis mesin cuci. Dengan kemasan ekonomis 5 liter, Anda bisa lebih hemat tanpa mengorbankan kualitas hasil cucian!",
                image: "/assets/img/detergent5L.png",
                stock: 5,
            },
            {
                id: 5,
                title: "Dryer Fogia 16 KG",
                originalPrice: 19000000,
                price: 18300000,
                description: "Dryer Fogia 16 KG adalah mesin pengering andalan untuk usaha laundry yang membutuhkan performa tinggi, hemat energi, dan hasil pengeringan maksimal. Dengan kapasitas besar 16 kg, mesin ini mampu mengeringkan pakaian dalam jumlah banyak dengan waktu yang lebih efisien. Dilengkapi fitur pengatur suhu otomatis, drum stainless steel tahan karat, serta sistem pemanas bertenaga gas atau listrik yang stabil, Dryer Fogia hadir sebagai solusi tepat untuk meningkatkan produktivitas usaha laundry Anda. Cocok untuk skala kecil hingga menengah dengan hasil kering merata dan siap setrika!",
                image: "/assets/img/DryerFogia16KG.png",
                stock: 5,
            },
            {
                id: 6,
                title: "Dryer Midea 7 KG",
                originalPrice: 89000000,
                price: 7000000,
                description: "Dryer Midea 7 KG adalah mesin pengering modern dengan desain elegan dan teknologi canggih yang ideal untuk kebutuhan rumah tangga atau laundry kecil. Dengan kapasitas 7 kg, dryer ini mampu mengeringkan pakaian dengan cepat dan efisien, dilengkapi fitur pengatur suhu, mode pengeringan lembut, serta sistem anti kusut untuk menjaga kualitas dan bentuk pakaian. Hemat listrik, mudah dioperasikan, dan memiliki drum stainless steel yang tahan lama—Dryer Midea adalah pilihan praktis untuk hasil cucian yang cepat kering, wangi, dan siap pakai setiap hari!",
                image: "/assets/img/DryerMidea7KG.png",
                stock: 5,
            },
            {
                id: 7,
                title: "Hanger",
                originalPrice: 15000,
                price: 10000,
                description: "Hanger kuat dan praktis ini dirancang untuk menjaga pakaian Anda tetap rapi dan bebas kerutan. Terbuat dari bahan berkualitas tinggi yang tahan lama, hanger ini cocok untuk segala jenis pakaian—dari baju, jaket, hingga dress. Desain ergonomisnya membuat gantungan mudah digunakan dan hemat tempat, ideal untuk lemari rumah maupun bisnis laundry. Dengan hanger ini, pakaian Anda akan tertata lebih rapi dan tampak selalu fresh setiap saat!",
                image: "/assets/img/Hanger.png",
                stock: 5,
            },
            {
                id: 8,
                title: "Isolasi Bening",
                originalPrice: 0,
                price: 0,
                description: "Isolasi Bening berkualitas tinggi ini hadir sebagai solusi praktis untuk kebutuhan pengepakan, perekat, dan perbaikan sehari-hari. Dengan daya rekat kuat dan transparansi yang jernih, isolasi ini mudah digunakan tanpa meninggalkan bekas, cocok untuk berbagai permukaan seperti kertas, plastik, dan kaca. Tahan lama dan fleksibel, isolasi bening ini sangat ideal untuk keperluan rumah, kantor, maupun usaha laundry yang butuh kemasan rapi dan aman!",
                image: "/assets/img/IsolasiBening.png",
                stock: 5,
            },
            {
                id: 9,
                title: "Jemuran",
                originalPrice: 350000 ,
                price: 300000,
                description: "Jemuran praktis dan kokoh ini dirancang untuk membantu pengeringan pakaian Anda secara optimal, dengan rangka kuat dan bahan anti karat yang tahan lama. Modelnya yang ringkas dan mudah dipindahkan membuatnya cocok untuk digunakan di dalam maupun luar ruangan, baik untuk laundry rumahan maupun usaha laundry profesional. Dengan kapasitas luas, jemuran ini mampu menampung banyak pakaian sekaligus, membuat proses pengeringan jadi lebih cepat dan efisien!",
                image: "/assets/img/Jemuran.png",
                stock: 5,
            },
            {
                id: 10,
                title: "Keranjang",
                originalPrice: 32000,
                price: 25000,
                description: "Keranjang multifungsi ini sangat praktis untuk menyimpan dan mengangkut pakaian kotor maupun bersih dengan mudah dan rapi. Terbuat dari bahan kuat dan ringan, keranjang ini tahan lama dan mudah dibersihkan, cocok untuk digunakan di rumah atau usaha laundry. Desain ergonomis dengan pegangan nyaman membuat aktivitas mengumpulkan dan memindahkan cucian jadi lebih efisien dan tanpa repot. Solusi tepat untuk menjaga kerapihan dan kelancaran proses laundry Anda!",
                image: "/assets/img/Keranjang.png",
                stock: 0,
            },
            {
                id: 11,
                title: "Meja Setrika",
                originalPrice: 900000,
                price: 800000,
                description: "Meja Setrika kokoh dan praktis ini dirancang untuk memudahkan proses menyetrika pakaian dengan permukaan yang luas dan stabil, sehingga hasil setrika lebih rapi tanpa khawatir bergoyang. Terbuat dari bahan berkualitas dengan lapisan tahan panas dan anti lengket, meja setrika ini juga mudah dilipat dan disimpan, cocok untuk rumah maupun usaha laundry. Dengan desain ergonomis dan kaki yang kuat, meja setrika ini siap mendukung kenyamanan dan kecepatan kerja Anda setiap hari!",
                image: "/assets/img/MejaSetrika.png",
                stock: 2,
            },
            {
                id: 12,
                title: "Parfume 1 Liter",
                originalPrice: 120000,
                price: 40000,
                description: "Parfum Baju 1 Liter ini menghadirkan kesegaran tahan lama yang membuat pakaian Anda selalu wangi dan nyaman dipakai. Dengan formula khusus yang lembut dan aman untuk semua jenis kain, parfum ini mudah digunakan setelah pencucian atau saat penyimpanan pakaian. Cocok untuk usaha laundry maupun penggunaan rumahan, kemasan 1 liter memberikan nilai ekonomis tanpa mengorbankan kualitas aroma yang menyegarkan sepanjang hari!",
                image: "/assets/img/Parfume1L.png",
                stock: 12,
            },
            {
                id: 13,
                title: "Parfume 5 Liter",
                originalPrice: 200000,
                price: 160000,
                description: "Parfum Baju 5 Liter ini adalah pilihan tepat untuk usaha laundry atau penggunaan rumah tangga yang membutuhkan aroma segar tahan lama dalam jumlah besar. Dengan formula berkualitas tinggi yang lembut di kain dan efektif menghilangkan bau tak sedap, parfum ini mudah diaplikasikan setelah proses pencucian untuk memberikan kesan wangi yang menyenangkan dan tahan lama. Kemasan besar 5 liter sangat ekonomis, membantu Anda menghemat biaya tanpa mengurangi kualitas kesegaran pakaian!",
                image: "/assets/img/Parfume5L.png",
                stock: 20,
            },
            {
                id: 14,
                title: "Parfume 600 ML",
                originalPrice: 30000,
                price: 25000,
                description: "Parfum Baju 600 ml ini menawarkan kesegaran tahan lama dengan kemasan praktis yang pas untuk kebutuhan rumah tangga maupun usaha laundry skala kecil. Dengan formula lembut yang aman untuk semua jenis kain, parfum ini mudah digunakan setelah mencuci untuk memberikan aroma wangi yang segar dan menenangkan. Ukurannya yang pas membuatnya mudah disimpan dan digunakan kapan saja, solusi ekonomis untuk menjaga pakaian selalu harum dan nyaman dipakai!",
                image: "/assets/img/Parfume600ML.png",
                stock: 20,
            },
            {
                id: 15,
                title: "Payung",
                originalPrice: 52000,
                price: 45000,
                description: "Payung kuat dan stylish ini dirancang untuk melindungi Anda dari hujan maupun terik matahari dengan bahan tahan air dan rangka yang kokoh. Desainnya yang elegan dan ringan membuat payung ini mudah dibawa kemana saja, cocok untuk penggunaan sehari-hari maupun sebagai perlengkapan usaha laundry atau toko. Dengan pilihan warna dan motif menarik, payung ini tidak hanya fungsional tetapi juga menambah gaya Anda saat cuaca tak menentu!",
                image: "/assets/img/Payung.png",
                stock: 20,
            },
            {
                id: 16,
                title: "Pemantik Dryer",
                originalPrice: 200000,
                price: 150000,
                description: "Pemantik Dryer ini adalah alat praktis dan andal untuk menyalakan mesin pengering berbahan bakar gas dengan mudah dan cepat. Dirancang khusus untuk memastikan penyalaan yang aman dan konsisten, pemantik ini membantu mempercepat proses pengoperasian dryer tanpa repot. Terbuat dari material tahan panas dan tahan lama, pemantik dryer ini menjadi solusi sempurna untuk menjaga kelancaran usaha laundry Anda setiap hari!",
                image: "/assets/img/PemantikDryer.png",
                stock: 20,
            },
            {
                id: 17,
                title: "Plastik HD 1 KG",
                originalPrice: 40000,
                price: 35000,
                description: "Plastik HD 1 KG (High-Density Polyethylene) ini adalah pilihan terbaik untuk kebutuhan pengemasan yang kuat, tahan sobek, dan fleksibel. Cocok digunakan untuk membungkus pakaian hasil laundry, barang dagangan, atau berbagai keperluan kemasan lainnya. Dengan ketebalan yang optimal, plastik ini menjaga kebersihan dan keamanan isi kemasan, sekaligus mudah digunakan dan ramah lingkungan. Solusi praktis dan ekonomis untuk bisnis atau kebutuhan rumah tangga Anda!",
                image: "/assets/img/PlastikHD1KG.png",
                stock: 20,
            },
            {
                id: 18,
                title: "Plastik PP 1 KG",
                originalPrice: 40000,
                price: 35000,
                description: "Plastik PP 1 KG (Polypropylene) ini adalah solusi kemasan yang kuat, transparan, dan tahan panas, cocok untuk membungkus pakaian laundry, produk makanan, atau barang-barang lainnya yang membutuhkan perlindungan ekstra. Plastik ini memiliki daya tahan tinggi terhadap tekanan dan gesekan, serta mudah dilipat dan disegel, menjadikannya pilihan ideal untuk usaha laundry maupun keperluan sehari-hari. Dengan berat 1 kg, kemasan ini ekonomis dan praktis untuk penggunaan jangka panjang!",
                image: "/assets/img/PlastikPP1KG.png",
                stock: 20,
            },
            {
                id: 19,
                title: "Setrika Listrik",
                originalPrice: 700000,
                price: 500000,
                description: "Setrika Listrik Philips menghadirkan performa handal dengan teknologi pemanasan cepat dan suhu yang stabil untuk hasil setrika yang rapi dan tahan lama. Desain ergonomis dan ringan membuatnya nyaman digunakan dalam waktu lama, sementara sol permukaan anti lengket memudahkan proses penyetrikaan tanpa merusak kain. Cocok untuk kebutuhan rumah tangga maupun usaha laundry kecil, setrika ini juga dilengkapi fitur pengatur suhu yang mudah diakses, menjadikan Setrika Philips pilihan tepat untuk menjaga pakaian selalu tampak prima!",
                image: "/assets/img/SetrikaListrik.png",
                stock: 20,
            },
            {
                id: 20,
                title: "Setrika Uap",
                originalPrice: 900000,
                price: 700000,
                description: "Setrika Uap ini adalah solusi praktis untuk mendapatkan pakaian yang halus dan bebas kerutan dengan cepat. Dilengkapi dengan teknologi uap yang kuat, setrika ini mampu menembus serat kain lebih dalam tanpa merusak bahan, sehingga pakaian tampak lebih rapi dan segar. Desain ergonomis dan fungsi pengatur suhu membuatnya mudah digunakan untuk berbagai jenis kain, cocok untuk kebutuhan rumah tangga maupun usaha laundry profesional. Dengan setrika uap ini, proses menyetrika jadi lebih efisien dan hasilnya maksimal!",
                image: "/assets/img/SetrikaUap.png",
                stock: 20,
            },
            {
                id: 21,
                title: "Timbangan 40 KG",
                originalPrice: 550000,
                price: 500000,
                description: "Timbangan Digital 40 KG ini adalah alat ukur presisi tinggi yang ideal untuk usaha laundry, toko, maupun kebutuhan bisnis lainnya. Dilengkapi dengan layar digital yang jelas dan mudah dibaca, timbangan ini mampu menimbang dengan akurasi tinggi hingga kapasitas 40 kilogram. Desainnya kokoh namun tetap ringan, serta mudah digunakan dengan fitur otomatis nol dan mati sendiri untuk menghemat daya. Solusi tepat untuk menambah efisiensi dan profesionalitas dalam operasional harian Anda!",
                image: "/assets/img/Timbangan40KG.png",
                stock: 20,
            },
            {
                id: 22,
                title: "Washer Aqua 10,5 KG",
                originalPrice: 0  ,
                price: 0,
                description: "Washer Aqua 10,5 KG adalah mesin cuci berkualitas tinggi yang dirancang untuk mencuci pakaian lebih bersih, cepat, dan hemat energi. Dengan kapasitas besar 10,5 kg, mesin ini cocok untuk kebutuhan rumah tangga besar maupun usaha laundry skala kecil hingga menengah. Dilengkapi dengan berbagai mode pencucian, teknologi hemat air, dan tabung stainless steel yang kuat dan tahan lama, Washer Aqua memberikan hasil cucian yang maksimal tanpa merusak serat kain. Pilihan tepat untuk Anda yang mengutamakan efisiensi dan keawetan!",
                image: "/assets/img/WasherAqua10KG.png",
                stock: 20,
            },
            {
                id: 23,
                title: "Washer LG 20 KG",
                originalPrice: 0,
                price: 0,
                description: "Washer LG 20 KG adalah mesin cuci berkapasitas besar yang dirancang untuk memenuhi kebutuhan cuci dalam volume tinggi dengan hasil maksimal. Ideal untuk usaha laundry profesional, mesin ini dilengkapi teknologi canggih dari LG seperti Inverter Direct Drive yang membuat proses pencucian lebih tenang, efisien, dan tahan lama. Tabung stainless steel yang kuat serta berbagai pilihan program pencucian membantu menjaga kualitas pakaian tetap prima meskipun dicuci dalam jumlah besar. Dengan performa tinggi dan hemat energi, Washer LG 20 KG siap mendukung operasional laundry Anda jadi lebih cepat dan efisien!",
                image: "/assets/img/WasherLG20KG.png",
                stock: 20,
            }

        ];